import type { CatalogTool } from '../types/index.js';

const catalog: CatalogTool[] = [
  {
    name: 'caveman',
    repo: 'anthropics/caveman',
    category: 'plugin',
    description: 'Token-saving plugin that reduces verbose output and optimizes context usage.',
    authRequired: false,
    networkRequired: 'none',
    installMethod: 'marketplace',
    installCommands: ['/install-plugin caveman'],
    prerequisites: [],
    tags: ['token-saving', 'universal', 'optimization'],
    maturityFit: ['greenfield', 'early', 'growing', 'mature'],
  },
  {
    name: 'planning-with-files',
    repo: 'anthropics/planning-with-files',
    category: 'skill',
    description: 'Structured planning skill that creates and manages implementation plans as files.',
    authRequired: false,
    networkRequired: 'none',
    installMethod: 'npx',
    installCommands: ['npx planning-with-files init'],
    prerequisites: [],
    tags: ['planning', 'universal', 'workflow'],
    maturityFit: ['greenfield', 'early', 'growing', 'mature'],
  },
  {
    name: 'impeccable',
    repo: 'anthropics/impeccable',
    category: 'plugin',
    description: 'Frontend and React design plugin that enforces design system conventions and best practices.',
    authRequired: false,
    networkRequired: 'none',
    installMethod: 'marketplace',
    installCommands: ['/install-plugin impeccable'],
    prerequisites: [],
    tags: ['frontend', 'react', 'design', 'ui'],
    maturityFit: ['early', 'growing', 'mature'],
  },
  {
    name: 'playwright-skill',
    repo: 'anthropics/playwright-skill',
    category: 'skill',
    description: 'End-to-end testing skill using Playwright for browser automation and frontend testing.',
    authRequired: false,
    networkRequired: 'none',
    installMethod: 'marketplace',
    installCommands: ['/install-plugin playwright-skill'],
    prerequisites: [],
    tags: ['testing', 'frontend', 'e2e', 'browser'],
    maturityFit: ['growing', 'mature'],
  },
  {
    name: 'get-shit-done',
    repo: 'anthropics/get-shit-done',
    category: 'skill',
    description: 'Spec-driven development skill for CLI tools that enforces structured implementation workflows.',
    authRequired: false,
    networkRequired: 'none',
    installMethod: 'npx',
    installCommands: ['npx get-shit-done init'],
    prerequisites: [],
    tags: ['spec-driven', 'cli', 'workflow', 'productivity'],
    maturityFit: ['greenfield', 'early', 'growing', 'mature'],
  },
  {
    name: 'claude-mem',
    repo: 'anthropics/claude-mem',
    category: 'plugin',
    description: 'Memory management plugin for long-running sessions, persisting context across conversations.',
    authRequired: false,
    networkRequired: 'none',
    installMethod: 'npx',
    installCommands: ['npx claude-mem init'],
    prerequisites: ['node >= 18'],
    tags: ['memory', 'long-running', 'context'],
    maturityFit: ['growing', 'mature'],
  },
  {
    name: 'graphify',
    repo: 'anthropics/graphify',
    category: 'agent',
    description: 'Knowledge graph builder for large codebases, mapping relationships between modules and symbols.',
    authRequired: false,
    networkRequired: 'partial',
    installMethod: 'pip',
    installCommands: ['pip install graphify'],
    prerequisites: ['python >= 3.10'],
    tags: ['knowledge-graph', 'large-codebase', 'analysis', 'visualization'],
    maturityFit: ['growing', 'mature'],
  },
  {
    name: 'cartographer',
    repo: 'anthropics/cartographer',
    category: 'plugin',
    description: 'Codebase mapping plugin that generates navigable maps of project structure and dependencies.',
    authRequired: false,
    networkRequired: 'none',
    installMethod: 'marketplace',
    installCommands: ['/install-plugin cartographer'],
    prerequisites: [],
    tags: ['codebase-mapping', 'navigation', 'architecture'],
    maturityFit: ['growing', 'mature'],
  },
  {
    name: 'trailofbits/skills',
    repo: 'trailofbits/skills',
    category: 'skill',
    description: 'Security-focused skills from Trail of Bits for vulnerability detection and secure coding.',
    authRequired: false,
    networkRequired: 'none',
    installMethod: 'marketplace',
    installCommands: ['/install-plugin trailofbits/skills'],
    prerequisites: [],
    tags: ['security', 'audit', 'vulnerability'],
    maturityFit: ['growing', 'mature'],
  },
  {
    name: 'everything-claude-code',
    repo: 'anthropics/everything-claude-code',
    category: 'workflow',
    description: 'Performance and token-saving collection of best-practice configurations and workflows.',
    authRequired: false,
    networkRequired: 'none',
    installMethod: 'git-clone',
    installCommands: ['git clone https://github.com/anthropics/everything-claude-code.git'],
    prerequisites: [],
    tags: ['performance', 'token-saving', 'best-practices', 'universal'],
    maturityFit: ['greenfield', 'early', 'growing', 'mature'],
  },
  {
    name: 'claude-hud',
    repo: 'anthropics/claude-hud',
    category: 'plugin',
    description: 'Monitoring dashboard plugin that tracks token usage, session metrics, and performance.',
    authRequired: false,
    networkRequired: 'none',
    installMethod: 'marketplace',
    installCommands: ['/install-plugin claude-hud'],
    prerequisites: ['node >= 18'],
    tags: ['monitoring', 'metrics', 'dashboard'],
    maturityFit: ['growing', 'mature'],
  },
  {
    name: 'homunculus',
    repo: 'anthropics/homunculus',
    category: 'agent',
    description: 'Pattern-learning agent that observes coding patterns and suggests improvements over time.',
    authRequired: false,
    networkRequired: 'none',
    installMethod: 'marketplace',
    installCommands: ['/install-plugin homunculus'],
    prerequisites: [],
    tags: ['pattern-learning', 'ai', 'automation'],
    maturityFit: ['growing', 'mature'],
  },
  {
    name: 'claude-octopus',
    repo: 'anthropics/claude-octopus',
    category: 'plugin',
    description: 'Multi-model orchestration plugin that coordinates between different AI models.',
    authRequired: true,
    networkRequired: 'full',
    installMethod: 'marketplace',
    installCommands: ['/install-plugin claude-octopus'],
    prerequisites: [],
    tags: ['multi-model', 'orchestration'],
    maturityFit: ['growing', 'mature'],
  },
  {
    name: 'call-me',
    repo: 'anthropics/call-me',
    category: 'plugin',
    description: 'Phone notification plugin that calls you when long-running tasks complete.',
    authRequired: true,
    networkRequired: 'full',
    installMethod: 'marketplace',
    installCommands: ['/install-plugin call-me'],
    prerequisites: [],
    tags: ['phone', 'notification', 'alerts'],
    maturityFit: ['growing', 'mature'],
  },
];

export function getCatalog(): CatalogTool[] {
  return catalog;
}

export function findToolByName(name: string): CatalogTool | null {
  return catalog.find((t) => t.name === name) ?? null;
}

export function getToolsByTag(tag: string): CatalogTool[] {
  return catalog.filter((t) => t.tags.includes(tag));
}
