import type { ProjectProfile } from '../types/index.js';

export interface AiProviderStatus {
  available: boolean;
  mode: 'ai' | 'local';
  reason: string;
}

export function detectAiProvider(): AiProviderStatus {
  const apiKey = process.env.ANTHROPIC_API_KEY;

  if (!apiKey) {
    return { available: false, mode: 'local', reason: 'ANTHROPIC_API_KEY not set' };
  }

  return { available: true, mode: 'ai', reason: 'API key configured' };
}

export async function enhanceWithAI(
  localDraft: string,
  profile: ProjectProfile,
  context: string,
): Promise<string> {
  const status = detectAiProvider();

  if (!status.available) {
    // Graceful fallback: return local draft as-is
    return localDraft;
  }

  try {
    // Dynamic import via variable to avoid TypeScript static resolution.
    // The SDK is intentionally NOT a dependency — it's optional.
    const sdkName = '@anthropic-ai/sdk';
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const sdkModule: any = await import(/* @vite-ignore */ sdkName);
    const Anthropic = sdkModule.default ?? sdkModule;
    const client = new Anthropic();

    const message = await client.messages.create({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 4096,
      messages: [{
        role: 'user',
        content: `You are improving a CLAUDE.md file for a project. Here is the current draft generated by rules:

---
${localDraft}
---

Project profile:
${JSON.stringify(profile, null, 2)}

Additional context:
${context}

Improve this CLAUDE.md to be more specific and helpful. Keep the slaminar ownership markers (<!-- slaminar:begin/end -->). Keep it concise. Output only the improved markdown, nothing else.`,
      }],
    });

    const textBlock = message.content.find((b: { type: string }) => b.type === 'text');
    return textBlock?.text ?? localDraft;
  } catch {
    // API call failed or SDK not installed — return local draft as fallback
    return localDraft;
  }
}
